savings_account = 10000
print("the toatal balance", savings_account)

credit = savings_account + 5000
print("credit of 5000Rs available balance is =", credit)

debit =credit - 1000
print("debit of 1000Rs available balance is =", debit)

credit = debit + 1000
print("credit of 5000Rs available balance is =", credit)

debit = credit - 6000
print("debit of 1000Rs available balance is =", debit)

print("10% intrest = ",debit*1*10//100)
print("after adding the 10% of intrest available balance is =", debit*1*10//100+debit )











