a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f"addition of {a}+{b} = {a+b}")

a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f"subtraction of {a}-{b} = {a-b}")

a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f"multiple of {a}*{b} = {a*b}")

a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f" division of {a}/{b} = {a/b}")

a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f"floor division of {a}//{b} = {a//b}")

a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f"module of {a}%{b} = {a%b}")

a = int(input ("enter the num of : "))
b = int(input ("enter the num of : "))
print(f"power of {a}**{b} = {a**b}")

